### ISSUE TITLE
"None of the Above"" does not exclude Aurora australis

### ISSUE THREAD

**Issue by HaxxonHax** [alexislours/MeteoNookAndroid#2]
When selecting "None of the above" under **Special Patterns**, this does not exclude the "Aurora australis" pattern.

To reproduce:
 - Set island to Southern Hemisphere
 - Select "Aurora australis" under **Special Patterns**, and check any of the boxes.  Note **Possible patterns**: Fine01, Fine03, Fine05.
 - Change **Special Patterns** to "None of the above".  Note **Possible patterns** includes those from previous step: Fine01, Fine03, Fine05.

**Comment by alexislours** [comment]
This repository is for the Android version of MeteoNook. This issue is outside of the scope of this repository and most likely should be brought up on the main repository instead of here.
